[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
wallet_buddhi = "EcorGtD2gpLK9FRGHCJwSd1PPRhVo2yDWYkpEvPfoogQ"

[programs.localnet]
wallet_buddhi = "EcorGtD2gpLK9FRGHCJwSd1PPRhVo2yDWYkpEvPfoogQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
